-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer_transactions
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    transaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    product_service character varying(100) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric NOT NULL,
    paid_amount numeric NOT NULL DEFAULT 0,
    remaining_amount numeric NOT NULL DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    payment_date date NOT NULL,
    next_payment_date date,
    rating integer,
    notes text COLLATE pg_catalog."default",
    payment_completed_at timestamp without time zone,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customer_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    mobile_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    pincode character varying(6) COLLATE pg_catalog."default" NOT NULL,
    village_city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    district character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(100) COLLATE pg_catalog."default" NOT NULL,
    complete_address text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_logs
(
    id serial NOT NULL,
    transaction_id integer NOT NULL,
    customer_id integer NOT NULL,
    amount numeric NOT NULL,
    payment_date date NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    rating integer,
    CONSTRAINT payment_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.session
(
    sid character varying COLLATE pg_catalog."default" NOT NULL,
    sess json NOT NULL,
    expire timestamp without time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (sid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    shop_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    owner_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    owner_phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    shop_address text COLLATE pg_catalog."default" NOT NULL,
    pincode character varying(15) COLLATE pg_catalog."default",
    tehsil character varying(100) COLLATE pg_catalog."default",
    district character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    shop_image character varying(255) COLLATE pg_catalog."default",
    slug character varying(500) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.customer_transactions
    ADD CONSTRAINT customer_transactions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_transactions
    ADD CONSTRAINT customer_transactions_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customers
    ADD CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_logs
    ADD CONSTRAINT payment_logs_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payment_logs
    ADD CONSTRAINT payment_logs_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.customer_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;